# Generated by Django 2.2.24 on 2022-01-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(choices=[(True, 'новостройка'), (False, 'старое здание'), (None, 'не заполнено')], db_index=True, default=None, verbose_name='Новостройка'),
        ),
    ]
