# Generated by Django 2.2.24 on 2022-01-03 11:31
import phonenumbers

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220103_1420'),
    ]

    def fill_pure_phonenumber(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            if flat.owners_phonenumber:
                pass
            #flat.save()


    operations = [
        migrations.RunPython(fill_pure_phonenumber),
    ]
