# Generated by Django 2.2.24 on 2022-01-05 10:10

from django.db import migrations


def fill_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    #for flat in Flat.objects.all():
    #    phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner),
    ]
