# Generated by Django 2.2.24 on 2022-01-05 15:57

from django.db import migrations


def fill_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        flat.flat_owners.set(
            Owner.objects.filter(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_fillOwner'),
    ]

    operations = [
        migrations.RunPython(fill_flat),
    ]
