# Generated by Django 2.2.24 on 2022-01-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_fillFlat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
